version: "3.2"

services:
  phpmyadmin5.6:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-mysql-5.6-192.168.1.3
    external_links:
      - mysql5.6-192.168.1.2:db
    networks:
       default:
          ipv4_address: 192.168.1.3
    restart: always
networks:
  default:
    external:
      name: devnetwork
